### ISSUE TITLE
Streamline "authoring" questions docs

### ISSUE THREAD

**Issue by firasm** [open-resources/physics_bank#54]
Hey @akshatpoddar , your recent PR (#52) now has two files that have overlapping content:

- https://firas.moosvi.com/oer/physicsbank/docs/authoring_questions.html 
- https://firas.moosvi.com/oer/physicsbank/docs/authoring.html

Could I please ask you to create a new PR and consolidate these two pages so the content isn't repeated ?

Maybe we need:

- one file with an overview of the the markdown and PL system (you can put the screenshots below in the md file as a place-holder for now)
- one file for a description of the tags, fields, etc of the markdown file
- one file for the steps to author the question

<img width="1338" alt="Screen Shot 2021-08-09 at 1 34 54 PM" src="https://user-images.githubusercontent.com/2507459/128770962-2a8b1cf7-500a-4968-ab8d-94b50cd019fc.png">
<img width="1337" alt="Screen Shot 2021-08-09 at 1 35 09 PM" src="https://user-images.githubusercontent.com/2507459/128770964-55a95262-6369-46fa-bec0-744ba86824b3.png">
<img width="1341" alt="Screen Shot 2021-08-09 at 1 35 01 PM" src="https://user-images.githubusercontent.com/2507459/128770969-a0a408e6-c50e-4e0d-9da9-369cba8992aa.png">

**Comment by akshatpoddar** [comment]
Hi! I read through this issue and would like to understand it more clearly.

So we want one html page displaying all the information for which I can consolidate all the information which I assumed I would do in one markdown file. 

But I got a bit confused when I read further about creating three different files for the different pieces of information.  Would we be able to display all the information on one page from these three different md files?

**Comment by firasm** [comment]
There are two parts: first part is to make sure no information is duplicated across the two pages. Second task is to then split it up into sensible subcomponents.

Once you do that, I will add them as "sub-pages" of one section (I can take care of this part if I have multiple files).

**Comment by akshatpoddar** [comment]
Alright, I would need the md file of the page: https://firas.moosvi.com/oer/physicsbank/docs/authoring_questions.html to get the information and images from there. Could you guide me to where I can find it?

**Comment by firasm** [comment]
https://github.com/open-resources/physics_bank/blob/main/docs/authoring_questions.md

**Comment by akshatpoddar** [comment]
Alright thank you! Also where do I insert the three images that you have provided? I have not mentioned how the whole process works with prairielearn and how the prairielearn files are generated and there are three files for it. I do not know which place in the content will be relevant for them to be inserted.

**Comment by firasm** [comment]
At the top of this issue, I gave some suggestions on where it could go:
 
> Maybe we need:
> 
> * one file with an overview of the the markdown and PL system (you can put the screenshots below in the md file as a place-holder for now)
> * one file for a description of the tags, fields, etc of the markdown file
> * one file for the steps to author the question

**Comment by firasm** [comment]
hey @michaelwkudla - once @akshatpoddar has gotten a little further along in this process, could you please review it and add your own commentary? This is important for posterity and for others to be able to duplicate what we did for other courses.

**Comment by michaelwkudla** [comment]
Will so. @akshatpoddar : add me as a reviewer or reply to this when you're ready or have any questions.

**Comment by firasm** [comment]
This is linked to PR #56 - which I think you just finished reviewing.

**Comment by firasm** [comment]
Done this in d45c92d2692dce48e529c71239e032679451f9ff
